# Generated by Django 5.2.5 on 2025-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouvert'), ('CLOSED', 'Fermé')], default='OPEN', max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CHECKING', 'Compte Courant'), ('SAVINGS', 'Compte Épargne')], max_length=16),
        ),
    ]
