# Generated by Django 5.2.5 on 2025-08-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processed',
            field=models.BooleanField(default=False, help_text='Traitée dans le solde (pour éviter double traitement via signaux)'),
        ),
    ]
